
name: Deploy

on: [push]

jobs:
  github_pages:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'web skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run: |
        cd web
        npm install
        npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: web/dist
  heroku:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'api skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Auth
      env: 
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU }}
      run: |
        tee ~/.netrc << END
        machine api.heroku.com
            login $email
            password $api_key
        machine git.heroku.com
            login $email
            password $api_key
        END
    - name: Setup Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Deploy to Heroku
      run: |
        heroku git:remote -a npe-env-test
        git subtree push --prefix api heroku master
    - name: Migrate DB
      run: |
        heroku run rails db:migrate